version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    volumes:
      - infoly-mongo-data:/data/db
    ports:
      - "27017:27017"
  infoly:
    image: docker.io/library/infoly:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/infoly


volumes:
  infoly-mongo-data: